from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QThread, pyqtSignal, pyqtSlot

class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 636)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(33, 33, 33);\n"
"color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.azimuthDisplayGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.azimuthDisplayGroup.setGeometry(QtCore.QRect(20, 10, 381, 231))
        self.azimuthDisplayGroup.setStyleSheet("")
        self.azimuthDisplayGroup.setObjectName("azimuthDisplayGroup")
        self.azimuthDialDisplay = QtWidgets.QDial(self.azimuthDisplayGroup)
        self.azimuthDialDisplay.setGeometry(QtCore.QRect(110, 50, 171, 161))
        self.azimuthDialDisplay.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.azimuthDialDisplay.setMaximum(360)
        self.azimuthDialDisplay.setTracking(True)
        self.azimuthDialDisplay.setInvertedControls(False)
        self.azimuthDialDisplay.setWrapping(True)
        self.azimuthDialDisplay.setNotchesVisible(True)
        self.azimuthDialDisplay.setObjectName("azimuthDialDisplay")
        self.azimuthLCDDisplay = QtWidgets.QLCDNumber(self.azimuthDisplayGroup)
        self.azimuthLCDDisplay.setGeometry(QtCore.QRect(160, 120, 71, 23))
        self.azimuthLCDDisplay.setObjectName("azimuthLCDDisplay")
        self.ccwButton = QtWidgets.QCommandLinkButton(self.azimuthDisplayGroup)
        self.ccwButton.setGeometry(QtCore.QRect(20, 20, 101, 71))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ccwButton.setIcon(icon)
        self.ccwButton.setIconSize(QtCore.QSize(50, 50))
        self.ccwButton.setObjectName("ccwButton")
        self.cwButton = QtWidgets.QCommandLinkButton(self.azimuthDisplayGroup)
        self.cwButton.setGeometry(QtCore.QRect(270, 20, 91, 71))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cwButton.setIcon(icon1)
        self.cwButton.setIconSize(QtCore.QSize(50, 50))
        self.cwButton.setObjectName("cwButton")
        self.elevationDisplayGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.elevationDisplayGroup.setGeometry(QtCore.QRect(410, 10, 391, 231))
        self.elevationDisplayGroup.setStyleSheet("")
        self.elevationDisplayGroup.setObjectName("elevationDisplayGroup")
        self.elevationDialDisplay = QtWidgets.QDial(self.elevationDisplayGroup)
        self.elevationDialDisplay.setGeometry(QtCore.QRect(110, 50, 171, 161))
        self.elevationDialDisplay.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.elevationDialDisplay.setMaximum(120)
        self.elevationDialDisplay.setSingleStep(1)
        self.elevationDialDisplay.setPageStep(10)
        self.elevationDialDisplay.setSliderPosition(0)
        self.elevationDialDisplay.setTracking(True)
        self.elevationDialDisplay.setOrientation(QtCore.Qt.Horizontal)
        self.elevationDialDisplay.setInvertedAppearance(False)
        self.elevationDialDisplay.setInvertedControls(False)
        self.elevationDialDisplay.setWrapping(False)
        self.elevationDialDisplay.setNotchTarget(3.7)
        self.elevationDialDisplay.setNotchesVisible(True)
        self.elevationDialDisplay.setObjectName("elevationDialDisplay")
        self.elevationLCDDisplay = QtWidgets.QLCDNumber(self.elevationDisplayGroup)
        self.elevationLCDDisplay.setGeometry(QtCore.QRect(160, 120, 71, 23))
        self.elevationLCDDisplay.setObjectName("elevationLCDDisplay")
        self.downButton = QtWidgets.QCommandLinkButton(self.elevationDisplayGroup)
        self.downButton.setGeometry(QtCore.QRect(280, 90, 111, 71))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon2)
        self.downButton.setIconSize(QtCore.QSize(50, 50))
        self.downButton.setObjectName("downButton")
        self.upButton = QtWidgets.QCommandLinkButton(self.elevationDisplayGroup)
        self.upButton.setGeometry(QtCore.QRect(10, 90, 91, 71))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon3)
        self.upButton.setIconSize(QtCore.QSize(50, 50))
        self.upButton.setObjectName("upButton")
        self.setPositionGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.setPositionGroup.setGeometry(QtCore.QRect(210, 280, 391, 291))
        self.setPositionGroup.setObjectName("setPositionGroup")
        self.azimuthDialInput = QtWidgets.QDial(self.setPositionGroup)
        self.azimuthDialInput.setGeometry(QtCore.QRect(20, 40, 171, 161))
        self.azimuthDialInput.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.azimuthDialInput.setMaximum(360)
        self.azimuthDialInput.setTracking(True)
        self.azimuthDialInput.setInvertedControls(False)
        self.azimuthDialInput.setWrapping(True)
        self.azimuthDialInput.setNotchesVisible(True)
        self.azimuthDialInput.setObjectName("azimuthDialInput")
        self.azimuthLCDDisplayInput = QtWidgets.QLCDNumber(self.setPositionGroup)
        self.azimuthLCDDisplayInput.setGeometry(QtCore.QRect(70, 110, 71, 23))
        self.azimuthLCDDisplayInput.setObjectName("azimuthLCDDisplayInput")
        self.elevationLCDDisplayInput = QtWidgets.QLCDNumber(self.setPositionGroup)
        self.elevationLCDDisplayInput.setGeometry(QtCore.QRect(250, 110, 71, 23))
        self.elevationLCDDisplayInput.setObjectName("elevationLCDDisplayInput")
        self.elevationDialInput = QtWidgets.QDial(self.setPositionGroup)
        self.elevationDialInput.setGeometry(QtCore.QRect(200, 40, 171, 161))
        self.elevationDialInput.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.elevationDialInput.setMaximum(120)
        self.elevationDialInput.setSingleStep(1)
        self.elevationDialInput.setPageStep(10)
        self.elevationDialInput.setSliderPosition(0)
        self.elevationDialInput.setTracking(True)
        self.elevationDialInput.setOrientation(QtCore.Qt.Horizontal)
        self.elevationDialInput.setInvertedAppearance(False)
        self.elevationDialInput.setInvertedControls(False)
        self.elevationDialInput.setWrapping(False)
        self.elevationDialInput.setNotchTarget(3.7)
        self.elevationDialInput.setNotchesVisible(True)
        self.elevationDialInput.setObjectName("elevationDialInput")
        self.azimuthLabel = QtWidgets.QLabel(self.setPositionGroup)
        self.azimuthLabel.setGeometry(QtCore.QRect(70, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.azimuthLabel.setFont(font)
        self.azimuthLabel.setStyleSheet("background-color: transparent;\n"
"font-weight: bold;\n"
"color: black;")
        self.azimuthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.azimuthLabel.setObjectName("azimuthLabel")
        self.elevationLabel = QtWidgets.QLabel(self.setPositionGroup)
        self.elevationLabel.setGeometry(QtCore.QRect(249, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.elevationLabel.setFont(font)
        self.elevationLabel.setStyleSheet("background-color: transparent;\n"
"font-weight: bold;\n"
"color: black;")
        self.elevationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.elevationLabel.setObjectName("elevationLabel")
        self.goPositionButton = QtWidgets.QPushButton(self.setPositionGroup)
        self.goPositionButton.setGeometry(QtCore.QRect(140, 240, 113, 32))
        self.goPositionButton.setStyleSheet("")
        self.goPositionButton.setObjectName("goPositionButton")
        self.elevationDialInput.raise_()
        self.azimuthDialInput.raise_()
        self.azimuthLCDDisplayInput.raise_()
        self.elevationLCDDisplayInput.raise_()
        self.azimuthLabel.raise_()
        self.elevationLabel.raise_()
        self.goPositionButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.azimuthDisplayGroup.setTitle(_translate("MainWindow", "Azimuth"))
        self.ccwButton.setText(_translate("MainWindow", "CCW"))
        self.cwButton.setText(_translate("MainWindow", "CW"))
        self.elevationDisplayGroup.setTitle(_translate("MainWindow", "Elevation"))
        self.downButton.setText(_translate("MainWindow", "DOWN"))
        self.upButton.setText(_translate("MainWindow", "UP"))
        self.setPositionGroup.setTitle(_translate("MainWindow", "Set Position Values"))
        self.azimuthLabel.setText(_translate("MainWindow", "Azimuth"))
        self.elevationLabel.setText(_translate("MainWindow", "Elevation"))
        self.goPositionButton.setText(_translate("MainWindow", "Go To Position"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
